# Generated by Django 2.2.12 on 2020-04-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='card_number',
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_super_man',
            field=models.BooleanField(default=False, help_text='Just custom is_admin field'),
        ),
    ]
