# Generated by Django 2.2.12 on 2020-04-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0002_myuser_card_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'my_user', 'verbose_name_plural': 'my_users'},
        ),
    ]
