# Generated by Django 2.2.12 on 2020-04-24 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0004_auto_20200423_1818'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myuser',
            unique_together={('first_name', 'last_name')},
        ),
    ]
