# Generated by Django 2.2.12 on 2020-04-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0005_auto_20200424_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='mobile',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
