# Generated by Django 2.2.12 on 2020-04-25 10:16

import auth_.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0006_auto_20200424_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='birthday',
            field=models.DateField(null=True, validators=[auth_.validators.validate_birthday]),
        ),
    ]
