# Generated by Django 2.2.12 on 2020-04-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_', '0007_auto_20200425_1016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myuser',
            unique_together=set(),
        ),
    ]
