# Generated by Django 2.2.12 on 2020-04-24 16:01

import city.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, validators=[city.validators.validate_name]),
        ),
    ]
