# Generated by Django 2.2.12 on 2020-04-24 22:44

import city.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20200424_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[city.validators.validate_name]),
        ),
    ]
