# Generated by Django 2.2.12 on 2020-04-23 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('type_by_size', models.CharField(choices=[('VS', 'Very Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('MG', 'MEGA')], default='M', max_length=2)),
                ('type_by_location', models.IntegerField(choices=[(1, 'Airport Hotel'), (2, 'Boatels'), (3, 'City Center'), (4, 'Motel'), (5, 'Suburb Hotels'), (6, 'Floating Hotels'), (7, 'Resorts'), (8, 'Rotels'), (9, 'Self-Catering Hotels')], default=1)),
                ('type_by_target', models.IntegerField(choices=[(1, 'Airport Hotel'), (2, 'Business Hotel'), (3, 'Bed and Breakfast Hotel'), (4, 'Casino Hotels'), (5, 'Resorts'), (6, 'Self-Catering Hotels'), (7, 'Service Apartments'), (8, 'Suite Hotels')], default=1)),
                ('type_by_star', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two-star'), (3, 'Three-star'), (4, 'Four-star'), (5, 'Five-start')], default=3)),
                ('address', models.CharField(default=None, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_images')),
                ('contact', models.CharField(max_length=20)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='city.City')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
    ]
