# Generated by Django 2.2.12 on 2020-04-25 13:00

from django.db import migrations, models
import django.db.models.deletion
import hotel.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[hotel.validators.validate_name])),
                ('description', models.CharField(max_length=255)),
                ('type_by_star', models.IntegerField(choices=[(1, 'One Star'), (2, 'Two-star'), (3, 'Three-star'), (4, 'Four-star'), (5, 'Five-start')], default=3)),
                ('address', models.CharField(default=None, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel_images', validators=[hotel.validators.validated_image])),
                ('contact', models.CharField(max_length=12, unique=True, validators=[hotel.validators.validated_contact])),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='city.City')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
    ]
