# Generated by Django 2.2.12 on 2020-04-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
