# Generated by Django 2.2.12 on 2020-04-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='likes',
        ),
    ]
