# Generated by Django 2.2.12 on 2020-04-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20200424_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='type_by_location',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='type_by_size',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='type_by_target',
        ),
    ]
