# Generated by Django 2.2.12 on 2020-04-22 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_hotel_likes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hotel',
            managers=[
            ],
        ),
    ]
