# Generated by Django 2.2.12 on 2020-04-21 21:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Single'), (2, 'Double'), (3, 'Triple'), (4, 'Quad')], default=1)),
                ('quest_id', models.IntegerField(blank=True, null=True)),
                ('reservation_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=10000)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.Hotel')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
            managers=[
                ('rooms_by_types', django.db.models.manager.Manager()),
            ],
        ),
    ]
