# Generated by Django 2.2.12 on 2020-04-25 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
